spring.config.import=optional:file:.env[.properties],optional:file:cinema-services/catalog-service/.env[.properties],optional:file:catalog-service/.env[.properties]
spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW}
spring.flyway.enabled=${FLYWAY_ENABLED}
spring.flyway.locations=${FLYWAY_LOCATIONS}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS}
management.endpoint.health.show-details=${HEALTH_SHOW_DETAILS}
app.gateway.secret=${INTERNAL_GATEWAY_SECRET}
app.internal.secret=${INTERNAL_SERVICE_SECRET}
app.jwt.secret=${JWT_SECRET}
app.quote.ttl-seconds=${QUOTE_TTL_SECONDS}
logging.pattern.level=${LOG_LEVEL_PATTERN}
