-- ==============================================================================
-- FLYWAY V3: ADD USER CINEMA ASSIGNMENTS (PostgreSQL)
-- Enforces: 1 Manager / Staff is assigned to strictly ONE cinema at any time
-- ==============================================================================

CREATE TABLE IF NOT EXISTS user_cinema_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    cinema_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_cinema_user_id ON user_cinema_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_cinema_cinema_id ON user_cinema_assignments(cinema_id);
