package com.cinemaai.booking.dto.response;

import com.cinemaai.booking.enums.BookingStatus;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public record BookingResponse(
        Long id,
        String bookingCode,
        Long userId,
        Long showtimeId,
        Long movieId,
        String movieTitle,
        String movieTitleSnapshot,
        String posterUrl,
        String moviePosterSnapshot,
        String cinemaName,
        String cinemaNameSnapshot,
        String roomName,
        String roomNameSnapshot,
        LocalDateTime showtimeStart,
        LocalDateTime showtimeStartSnapshot,
        BigDecimal subtotal,
        BigDecimal discountAmount,
        int loyaltyPointsRedeemed,
        BigDecimal totalAmount,
        BookingStatus status,
        LocalDateTime holdExpiresAt,
        LocalDateTime paidAt,
        LocalDateTime checkedInAt,
        LocalDateTime cancelledAt,
        LocalDateTime refundedAt,
        String qrCode,
        List<BookingSeatResponse> seats,
        List<BookingTicketResponse> tickets,
        List<BookingFoodResponse> foods,
        LocalDateTime createdAt
) {}
