spring.application.name=booking-service
spring.config.import=optional:file:.env[.properties],optional:file:cinema-services/booking-service/.env[.properties],optional:file:services/booking-service/.env[.properties],optional:file:booking-service/.env[.properties]

server.port=${SERVER_PORT}


# Database Configuration (Port 5433)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

## RabbitMQ (Event Broker)
#spring.rabbitmq.host=${RABBITMQ_HOST}
#spring.rabbitmq.port=${RABBITMQ_PORT}
#spring.rabbitmq.username=${RABBITMQ_USERNAME}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Catalog Internal Service URL
catalog.service.url=${CATALOG_SERVICE_URL}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Gateway Security (Zero-trust: only API Gateway is allowed)
app.gateway.secret=${INTERNAL_GATEWAY_SECRET:8F78D52690EED1A48867F89272F07391B8FBC8968F187BB5C53C60E20243D7AD}
app.gateway.url=${GATEWAY_URL:http://localhost:8080}

# SpringDoc OpenAPI (Swagger UI disabled on microservice port 8083, only api-docs enabled for Gateway)
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
