-- PostgreSQL migration for the existing user_roles model. Existing role IDs are unchanged.
ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_name_check;
ALTER TABLE roles ADD CONSTRAINT roles_name_check
    CHECK (name IN ('ADMIN', 'MANAGER', 'STAFF', 'CUSTOMER'));

INSERT INTO roles (name, created_at, updated_at)
SELECT 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'MANAGER');

CREATE TABLE IF NOT EXISTS manager_cinema_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    cinema_id BIGINT NOT NULL REFERENCES cinemas(id),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_manager_cinema UNIQUE (user_id, cinema_id)
);
CREATE INDEX IF NOT EXISTS idx_manager_cinema_assignments_cinema ON manager_cinema_assignments(cinema_id);

CREATE TABLE IF NOT EXISTS movie_edit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(id),
    requested_by BIGINT NOT NULL REFERENCES users(id),
    reviewed_by BIGINT REFERENCES users(id),
    status VARCHAR(20) NOT NULL,
    proposed_data TEXT NOT NULL,
    reason TEXT,
    rejection_reason TEXT,
    reviewed_at TIMESTAMP(6),
    version BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movie_edit_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);
CREATE INDEX IF NOT EXISTS idx_movie_edit_requests_movie ON movie_edit_requests(movie_id);
CREATE INDEX IF NOT EXISTS idx_movie_edit_requests_status ON movie_edit_requests(status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_edit_pending_per_movie ON movie_edit_requests(movie_id) WHERE status = 'PENDING';
