-- Migration V14: Hero Banner Management
-- Creates hero_banners and hero_banner_cinemas tables

CREATE TABLE IF NOT EXISTS hero_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(500),
    description TEXT,
    badge VARCHAR(100),
    format_label VARCHAR(100),
    desktop_image_url VARCHAR(1000) NOT NULL,
    mobile_image_url VARCHAR(1000),
    alt_text VARCHAR(255),
    focal_point VARCHAR(50) NOT NULL DEFAULT 'CENTER',
    linked_movie_id BIGINT REFERENCES movies(id) ON DELETE SET NULL,
    linked_promotion_id BIGINT REFERENCES promotions(id) ON DELETE SET NULL,
    primary_cta_type VARCHAR(50) NOT NULL DEFAULT 'BOOK_NOW',
    primary_cta_label VARCHAR(100) NOT NULL DEFAULT 'ĐẶT VÉ NGAY',
    primary_cta_url VARCHAR(1000),
    secondary_cta_type VARCHAR(50) DEFAULT 'NONE',
    secondary_cta_label VARCHAR(100),
    secondary_cta_url VARCHAR(1000),
    scope_type VARCHAR(50) NOT NULL DEFAULT 'GLOBAL',
    target_city VARCHAR(100),
    priority INT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 1,
    slide_duration_seconds INT NOT NULL DEFAULT 6,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    impressions_count BIGINT NOT NULL DEFAULT 0,
    clicks_count BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    published_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_banner_type CHECK (type IN ('MOVIE', 'PROMOTION', 'FNB', 'EVENT', 'MEMBERSHIP', 'CUSTOM')),
    CONSTRAINT chk_banner_status CHECK (status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'PAUSED', 'EXPIRED', 'ARCHIVED')),
    CONSTRAINT chk_banner_scope CHECK (scope_type IN ('GLOBAL', 'CITY', 'CINEMA')),
    CONSTRAINT chk_banner_focal_point CHECK (focal_point IN ('LEFT', 'CENTER', 'RIGHT')),
    CONSTRAINT chk_banner_cta_type CHECK (primary_cta_type IN ('BOOK_NOW', 'VIEW_MOVIE', 'VIEW_PROMOTION', 'VIEW_FNB', 'VIEW_EVENT', 'MEMBERSHIP', 'INTERNAL_URL', 'EXTERNAL_URL', 'NONE'))
);

CREATE INDEX IF NOT EXISTS idx_hero_banners_status ON hero_banners(status);
CREATE INDEX IF NOT EXISTS idx_hero_banners_schedule ON hero_banners(status, start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_hero_banners_sort ON hero_banners(sort_order, priority DESC);
CREATE INDEX IF NOT EXISTS idx_hero_banners_type ON hero_banners(type);
CREATE INDEX IF NOT EXISTS idx_hero_banners_scope ON hero_banners(scope_type);
CREATE INDEX IF NOT EXISTS idx_hero_banners_movie ON hero_banners(linked_movie_id);
CREATE INDEX IF NOT EXISTS idx_hero_banners_promotion ON hero_banners(linked_promotion_id);

CREATE TABLE IF NOT EXISTS hero_banner_cinemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_banner_id BIGINT NOT NULL REFERENCES hero_banners(id) ON DELETE CASCADE,
    cinema_id BIGINT NOT NULL REFERENCES cinemas(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_hero_banner_cinema UNIQUE (hero_banner_id, cinema_id)
);

CREATE INDEX IF NOT EXISTS idx_hero_banner_cinemas_banner ON hero_banner_cinemas(hero_banner_id);
CREATE INDEX IF NOT EXISTS idx_hero_banner_cinemas_cinema ON hero_banner_cinemas(cinema_id);

-- Seed initial banners so Landing Page immediately renders real data without hardcoding
INSERT INTO hero_banners (
    name, type, title, subtitle, badge, format_label,
    desktop_image_url, mobile_image_url, focal_point,
    primary_cta_type, primary_cta_label, primary_cta_url,
    secondary_cta_type, secondary_cta_label, secondary_cta_url,
    scope_type, priority, sort_order, slide_duration_seconds,
    status, impressions_count, clicks_count, published_at
)
SELECT
    'Dune: Part Two Premiere', 'CUSTOM', 'DUNE: HÀNH TINH CÁT - PHẦN HAI',
    'Trải nghiệm đỉnh cao phòng vé với định dạng IMAX Laser 70mm', 'BOM TẤN ĐANG CHIẾU', 'IMAX LASER 70MM',
    'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    'https://image.tmdb.org/t/p/w780/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', 'CENTER',
    'BOOK_NOW', 'ĐẶT VÉ NGAY', '/showtimes',
    'INTERNAL_URL', 'XEM TRAILER', 'https://www.youtube.com/watch?v=Way9Dexny3w',
    'GLOBAL', 10, 1, 6,
    'PUBLISHED', 0, 0, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM hero_banners WHERE name = 'Dune: Part Two Premiere');

INSERT INTO hero_banners (
    name, type, title, subtitle, badge, format_label,
    desktop_image_url, mobile_image_url, focal_point,
    primary_cta_type, primary_cta_label, primary_cta_url,
    secondary_cta_type, secondary_cta_label, secondary_cta_url,
    scope_type, priority, sort_order, slide_duration_seconds,
    status, impressions_count, clicks_count, published_at
)
SELECT
    'Deadpool & Wolverine Blockbuster', 'CUSTOM', 'DEADPOOL & WOLVERINE',
    'Hỗn loạn đa vũ trụ Marvel - Trải nghiệm âm thanh Dolby Atmos bùng nổ', 'BOM TẤN ĐANG CHIẾU', 'DOLBY ATMOS 3D',
    'https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    'https://image.tmdb.org/t/p/w780/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg', 'CENTER',
    'BOOK_NOW', 'ĐẶT VÉ NGAY', '/showtimes',
    'INTERNAL_URL', 'XEM TRAILER', 'https://www.youtube.com/watch?v=73_1biulkYk',
    'GLOBAL', 9, 2, 6,
    'PUBLISHED', 0, 0, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM hero_banners WHERE name = 'Deadpool & Wolverine Blockbuster');

INSERT INTO hero_banners (
    name, type, title, subtitle, badge, format_label,
    desktop_image_url, mobile_image_url, focal_point,
    primary_cta_type, primary_cta_label, primary_cta_url,
    secondary_cta_type, secondary_cta_label, secondary_cta_url,
    scope_type, priority, sort_order, slide_duration_seconds,
    status, impressions_count, clicks_count, published_at
)
SELECT
    'Gladiator II Epic', 'CUSTOM', 'VÕ SĨ GIÁC ĐẤU II',
    'Sự trở lại của đấu trường La Mã huyền thoại - Đạo diễn Ridley Scott', 'SẮP KHỞI CHIẾU', '4DX LASER',
    'https://image.tmdb.org/t/p/w1280/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg',
    'https://image.tmdb.org/t/p/w780/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg', 'CENTER',
    'BOOK_NOW', 'CHI TIẾT PHIM', '/movies',
    'INTERNAL_URL', 'XEM TRAILER', 'https://www.youtube.com/watch?v=4rgYUipGJNo',
    'GLOBAL', 8, 3, 6,
    'PUBLISHED', 0, 0, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM hero_banners WHERE name = 'Gladiator II Epic');
