-- ==============================================================================
-- PAYMENT SERVICE SCHEMA (Flyway V1 Migration)
-- Strict database isolation: Zero Foreign Keys across services.
-- Uses Logical IDs: booking_id, food_order_id, user_id.
-- Includes Transactional Outbox Pattern for resilient event-driven architecture.
-- ==============================================================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    food_order_id BIGINT,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    transaction_id VARCHAR(100),
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_url TEXT,
    payment_account_label VARCHAR(100),
    callback_payload TEXT,
    paid_at TIMESTAMP,
    refund_amount NUMERIC(12,2),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE cine_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    balance NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES cine_wallets(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    booking_id BIGINT,
    type VARCHAR(30) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    balance_after NUMERIC(12,2) NOT NULL,
    reference_code VARCHAR(100),
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Transactional Outbox Table
CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP
);

CREATE INDEX idx_payments_booking_id ON payments(booking_id);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_outbox_events_status_created ON outbox_events(status, created_at);
