-- ==============================================================================
-- PAYMENT SERVICE SCHEMA SYNC (Flyway V2 Migration)
-- Add any missing columns or tables from pre-existing or baselined database
-- ==============================================================================

-- 1. Ensure cine_wallets table exists
CREATE TABLE IF NOT EXISTS cine_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    balance NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Ensure wallet_transactions table exists
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES cine_wallets(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    booking_id BIGINT,
    type VARCHAR(30) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    balance_after NUMERIC(12,2) NOT NULL,
    reference_code VARCHAR(100),
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Ensure payments table exists
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    food_order_id BIGINT,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    transaction_id VARCHAR(100),
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_url TEXT,
    payment_account_label VARCHAR(100),
    callback_payload TEXT,
    paid_at TIMESTAMP,
    refund_amount NUMERIC(12,2),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Ensure payments has all required columns if table already existed
ALTER TABLE payments ADD COLUMN IF NOT EXISTS food_order_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_account_label VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS callback_payload TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_amount NUMERIC(12,2);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP;

-- 5. Ensure outbox_events table exists
CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_status_created ON outbox_events(status, created_at);
