-- ==============================================================================
-- PAYMENT SERVICE SCHEMA (Flyway V4 Migration)
-- Add withdrawal_requests table for CineWallet cash-out requests
-- ==============================================================================

CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES cine_wallets(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    account_holder VARCHAR(120) NOT NULL,
    wallet_phone VARCHAR(20),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    processed_method VARCHAR(50),
    processed_note VARCHAR(500),
    processed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON withdrawal_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status_created ON withdrawal_requests(status, created_at);
