-- ==============================================================================
-- PAYMENT SERVICE SCHEMA SYNC (Flyway V5 Migration)
-- Add loyalty point transactions audit trail table
-- ==============================================================================

CREATE TABLE IF NOT EXISTS loyalty_point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    booking_id BIGINT,
    booking_code VARCHAR(100),
    type VARCHAR(30) NOT NULL,
    points_delta INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    note VARCHAR(500),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_loyalty_tx_user ON loyalty_point_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_tx_booking ON loyalty_point_transactions(booking_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_tx_type ON loyalty_point_transactions(type);
CREATE INDEX IF NOT EXISTS idx_loyalty_tx_occurred_at ON loyalty_point_transactions(occurred_at);
