-- ==============================================================================
-- PAYMENT SERVICE SCHEMA (Flyway V7 Migration)
-- Add cinema-specific loyalty configurations table
-- ==============================================================================

CREATE TABLE IF NOT EXISTS loyalty_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT UNIQUE,
    cinema_name VARCHAR(255),
    earning_rate_percent NUMERIC(5,2) NOT NULL DEFAULT 1.00,
    redemption_rate_percent NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    redemption_points INT NOT NULL DEFAULT 1000,
    redemption_value_vnd NUMERIC(12,2) NOT NULL DEFAULT 1000.00,
    max_redemption_percent NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    expiry_month INT NOT NULL DEFAULT 12,
    expiry_day INT NOT NULL DEFAULT 31,
    expiry_time VARCHAR(8) NOT NULL DEFAULT '23:59:59',
    expiry_date VARCHAR(20),
    last_expired_at TIMESTAMP,
    last_reset_at TIMESTAMP,
    last_reset_source VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_loyalty_cfg_cinema ON loyalty_configurations(cinema_id);

-- Insert global default configuration (cinema_id IS NULL)
INSERT INTO loyalty_configurations (
    cinema_id,
    cinema_name,
    earning_rate_percent,
    redemption_rate_percent,
    redemption_points,
    redemption_value_vnd,
    max_redemption_percent,
    expiry_month,
    expiry_day,
    expiry_time
)
SELECT NULL, 'Toàn hệ thống (Mặc định)', 1.00, 100.00, 1000, 1000.00, 100.00, 12, 31, '23:59:59'
WHERE NOT EXISTS (SELECT 1 FROM loyalty_configurations WHERE cinema_id IS NULL);
