-- Migration V12: Create reviews and review_reports tables
-- Supports end-to-end movie rating & review system with verified bookings and moderation

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    user_email VARCHAR(255),
    user_full_name VARCHAR(255),
    booking_id BIGINT,
    rating INT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PUBLISHED',
    verified_booking BOOLEAN NOT NULL DEFAULT FALSE,
    report_count INT NOT NULL DEFAULT 0,
    contains_spoiler BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_at TIMESTAMP(6),
    hidden_by VARCHAR(255),
    moderation_reason VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_review_rating CHECK (rating >= 1 AND rating <= 10),
    CONSTRAINT chk_review_status CHECK (status IN ('PUBLISHED', 'FLAGGED', 'HIDDEN', 'REJECTED', 'VISIBLE', 'DELETED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reviews_user_movie
ON reviews(user_id, movie_id)
WHERE status NOT IN ('REJECTED', 'DELETED');

CREATE INDEX IF NOT EXISTS idx_reviews_movie_status ON reviews(movie_id, status);
CREATE INDEX IF NOT EXISTS idx_reviews_status_created ON reviews(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_booking ON reviews(booking_id);

CREATE TABLE IF NOT EXISTS review_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    reporter_user_id BIGINT NOT NULL,
    reporter_email VARCHAR(255),
    reason VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_report_reason CHECK (reason IN ('SPAM', 'INAPPROPRIATE', 'SPOILER', 'HARASSMENT', 'OFF_TOPIC', 'OTHER')),
    CONSTRAINT chk_report_status CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_review_reports_user_review
ON review_reports(reporter_user_id, review_id);

CREATE INDEX IF NOT EXISTS idx_review_reports_review ON review_reports(review_id);
