-- No foreign keys to Identity or Booking databases.
CREATE TABLE cinemas (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255) NOT NULL, address VARCHAR(500) NOT NULL, city VARCHAR(100), phone VARCHAR(20),
 status VARCHAR(30) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE movies (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title VARCHAR(255) NOT NULL UNIQUE, description TEXT, trailer_url VARCHAR(500), poster_url VARCHAR(500), avatar_url VARCHAR(500),
 duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0), release_date DATE, end_date DATE,
 language VARCHAR(50), subtitle_language VARCHAR(50), status VARCHAR(30) NOT NULL, age_rating VARCHAR(20),
 director VARCHAR(255), main_actors VARCHAR(1000), cast_list TEXT,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE genres (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(1000),
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE actors (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, biography VARCHAR(1000), avatar_url VARCHAR(500),
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE movie_genres (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id BIGINT NOT NULL REFERENCES movies(id), genre_id BIGINT NOT NULL REFERENCES genres(id),
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(movie_id, genre_id)
);
CREATE TABLE movie_actors (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id BIGINT NOT NULL REFERENCES movies(id), actor_id BIGINT NOT NULL REFERENCES actors(id),
 is_main_actor BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(movie_id, actor_id)
);
CREATE TABLE rooms (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cinema_id BIGINT NOT NULL REFERENCES cinemas(id), name VARCHAR(100) NOT NULL,
 room_type VARCHAR(30) NOT NULL, row_count INTEGER NOT NULL CHECK (row_count > 0), column_count INTEGER NOT NULL CHECK (column_count > 0),
 status VARCHAR(30) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(cinema_id, name)
);
CREATE TABLE seat_rows (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room_id BIGINT NOT NULL REFERENCES rooms(id), row_label VARCHAR(10) NOT NULL,
 display_order INTEGER NOT NULL, start_column INTEGER NOT NULL, row_type VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(room_id, row_label), UNIQUE(room_id, display_order)
);
CREATE TABLE seats (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room_id BIGINT NOT NULL REFERENCES rooms(id), seat_row_id BIGINT NOT NULL REFERENCES seat_rows(id),
 row_label VARCHAR(10) NOT NULL, seat_number INTEGER NOT NULL, display_column INTEGER NOT NULL,
 seat_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(room_id, row_label, seat_number)
);
CREATE TABLE showtimes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id BIGINT NOT NULL REFERENCES movies(id), room_id BIGINT NOT NULL REFERENCES rooms(id),
 start_time TIMESTAMP NOT NULL, end_time TIMESTAMP NOT NULL,
 base_price NUMERIC(12,2) NOT NULL CHECK (base_price >= 0), vip_price NUMERIC(12,2), couple_price NUMERIC(12,2),
 adult_standard_price NUMERIC(12,2), child_standard_price NUMERIC(12,2), student_standard_price NUMERIC(12,2),
 adult_vip_price NUMERIC(12,2), child_vip_price NUMERIC(12,2), student_vip_price NUMERIC(12,2),
 adult_couple_price NUMERIC(12,2), child_couple_price NUMERIC(12,2), student_couple_price NUMERIC(12,2),
 weekend_surcharge BOOLEAN NOT NULL, holiday_surcharge BOOLEAN NOT NULL, late_night_surcharge_amount NUMERIC(12,2) NOT NULL,
 status VARCHAR(30) NOT NULL, cancellation_reason TEXT, cancelled_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CHECK(end_time > start_time)
);
CREATE TABLE food_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, description VARCHAR(500),
 price NUMERIC(12,2) NOT NULL CHECK(price >= 0), image_url VARCHAR(500), status VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE food_combos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT,
 price NUMERIC(12,2) NOT NULL CHECK(price >= 0), image_url VARCHAR(500), status VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE ticket_pricing_rules (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ticket_type VARCHAR(30) NOT NULL, room_type VARCHAR(30) NOT NULL,
 seat_type VARCHAR(30), weekend BOOLEAN NOT NULL, holiday BOOLEAN NOT NULL,
 price NUMERIC(12,2) NOT NULL CHECK(price >= 0), active BOOLEAN NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE ticket_combos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, description VARCHAR(500),
 adult_count INTEGER NOT NULL, child_count INTEGER NOT NULL, student_count INTEGER NOT NULL,
 price NUMERIC(12,2) NOT NULL CHECK(price >= 0), active BOOLEAN NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_movies_status_release_id ON movies(status, release_date, id);
CREATE INDEX idx_movie_actors_actor_movie ON movie_actors(actor_id, movie_id);
CREATE INDEX idx_movie_genres_genre_movie ON movie_genres(genre_id, movie_id);
CREATE INDEX idx_showtimes_movie ON showtimes(movie_id);
CREATE INDEX idx_showtimes_room_start ON showtimes(room_id, start_time, end_time);
CREATE INDEX idx_showtimes_start_time ON showtimes(start_time);
