CREATE TABLE directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    biography TEXT,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE movie_directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES directors(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_movie_directors UNIQUE(movie_id, director_id)
);

CREATE INDEX idx_movie_directors_movie ON movie_directors(movie_id);
CREATE INDEX idx_movie_directors_director ON movie_directors(director_id);

-- Convert distinct existing movies.director values into directors
INSERT INTO directors (name, created_at, updated_at)
SELECT DISTINCT TRIM(director), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM movies
WHERE director IS NOT NULL AND TRIM(director) <> ''
  AND TRIM(director) NOT IN (SELECT name FROM directors);

-- Link movies to migrated Director records
INSERT INTO movie_directors (movie_id, director_id, created_at, updated_at)
SELECT m.id, d.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM movies m
JOIN directors d ON TRIM(m.director) = d.name
WHERE NOT EXISTS (
    SELECT 1 FROM movie_directors md WHERE md.movie_id = m.id AND md.director_id = d.id
);
