-- V9: Add cinema_audience_prices table
-- Stores the additional price surcharge per audience type (CHILD, STUDENT, ADULT) per cinema.
-- Final ticket price = room seat price + additional_price for audience type.
-- Couple seat: final price = couple_seat_price + additional_price(guest1) + additional_price(guest2).

CREATE TABLE cinema_audience_prices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id   BIGINT       NOT NULL,
    audience_type VARCHAR(20) NOT NULL CHECK (audience_type IN ('CHILD', 'STUDENT', 'ADULT')),
    additional_price NUMERIC(12, 2) NOT NULL CHECK (additional_price >= 0),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cinema_audience UNIQUE (cinema_id, audience_type)
);

CREATE INDEX idx_cinema_audience_prices_cinema ON cinema_audience_prices(cinema_id);
