-- ==============================================================================
-- BOOKING SERVICE SCHEMA (Flyway V1 Migration)
-- Strict database isolation: Zero Foreign Keys across services.
-- Uses Logical IDs: user_id, showtime_id, movie_id, seat_id, product_id.
-- ==============================================================================

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    movie_title_snapshot VARCHAR(255) NOT NULL,
    movie_poster_snapshot VARCHAR(500),
    cinema_name_snapshot VARCHAR(150) NOT NULL,
    room_name_snapshot VARCHAR(100) NOT NULL,
    showtime_start_snapshot TIMESTAMP NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    loyalty_points_redeemed INTEGER NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    hold_expires_at TIMESTAMP,
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    checked_in_at TIMESTAMP,
    refund_requested_at TIMESTAMP,
    refunded_at TIMESTAMP,
    refund_reason VARCHAR(255),
    qr_code TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE booking_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    showtime_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    row_label VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_type VARCHAR(30) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    ticket_code VARCHAR(60) UNIQUE,
    qr_code TEXT,
    ticket_type VARCHAR(30),
    checked_in_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE booking_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    seat_id BIGINT,
    ticket_type VARCHAR(30) NOT NULL,
    viewer_age INTEGER,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE booking_food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    is_combo BOOLEAN NOT NULL DEFAULT false,
    product_name_snapshot VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE food_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_order_code VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    booking_id BIGINT,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE food_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_order_id BIGINT NOT NULL REFERENCES food_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    is_combo BOOLEAN NOT NULL DEFAULT false,
    product_name_snapshot VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE processed_events (
    event_id VARCHAR(100) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMP NOT NULL
);

-- Indexing for high performance lookup & concurrency locking
CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_showtime ON bookings(showtime_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_booking_seats_showtime_seat ON booking_seats(showtime_id, seat_id);
CREATE INDEX idx_booking_seats_booking ON booking_seats(booking_id);
CREATE INDEX idx_food_orders_user ON food_orders(user_id);
