-- ==============================================================================
-- BOOKING SERVICE SCHEMA SYNC (Flyway V2 Migration)
-- Add any missing columns or tables from pre-existing or baselined database
-- ==============================================================================

-- 1. Ensure food_orders table exists
CREATE TABLE IF NOT EXISTS food_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_order_code VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    booking_id BIGINT,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Ensure food_order_items table exists
CREATE TABLE IF NOT EXISTS food_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_order_id BIGINT NOT NULL REFERENCES food_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    is_combo BOOLEAN NOT NULL DEFAULT false,
    product_name_snapshot VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Ensure booking_tickets table exists
CREATE TABLE IF NOT EXISTS booking_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    seat_id BIGINT,
    ticket_type VARCHAR(30) NOT NULL,
    viewer_age INTEGER,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Ensure booking_food_items table exists
CREATE TABLE IF NOT EXISTS booking_food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    is_combo BOOLEAN NOT NULL DEFAULT false,
    product_name_snapshot VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Ensure processed_events table exists for idempotent listener
CREATE TABLE IF NOT EXISTS processed_events (
    event_id VARCHAR(100) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. Add is_combo if booking_food_items / food_order_items already existed without it
ALTER TABLE booking_food_items ADD COLUMN IF NOT EXISTS is_combo BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE food_order_items ADD COLUMN IF NOT EXISTS is_combo BOOLEAN NOT NULL DEFAULT false;

-- 7. Ensure bookings has all required snapshot and lifecycle columns
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS movie_title_snapshot VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS movie_poster_snapshot VARCHAR(500);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cinema_name_snapshot VARCHAR(150);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS room_name_snapshot VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS showtime_start_snapshot TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS hold_expires_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS qr_code TEXT;

-- 8. Ensure booking_seats has all required columns
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS ticket_code VARCHAR(60);
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS qr_code TEXT;
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS ticket_type VARCHAR(30);
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMP;
