-- ==============================================================================
-- FLYWAY V3: ADD CINEMA_ID AND TICKET AUDIT LOGS (PostgreSQL)
-- ==============================================================================

-- 1. Add cinema_id to bookings table for multi-cinema isolation and fast filtering
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cinema_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_bookings_cinema_id ON bookings(cinema_id);

-- 2. Create ticket_audit_logs table to record cancel and refund operations
CREATE TABLE IF NOT EXISTS ticket_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    ticket_code VARCHAR(60),
    cinema_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_email VARCHAR(100),
    actor_role VARCHAR(30) NOT NULL,
    action VARCHAR(30) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    reason VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ticket_audit_cinema ON ticket_audit_logs(cinema_id);
CREATE INDEX IF NOT EXISTS idx_ticket_audit_booking ON ticket_audit_logs(booking_id);
CREATE INDEX IF NOT EXISTS idx_ticket_audit_created ON ticket_audit_logs(created_at);
